### ISSUE TITLE
sample code does not work

### ISSUE THREAD

**Issue by ghost** [wallee-payment/php-sdk#1]
The sample code does not work.

Apart from the variable naming which is not correct
e.g. $client is initialised but then $apiClient is used
same goes for $services and $apiService

even after fixing the above, i do get the following exception

Wallee\Sdk\ApiException: [1217B46F-7AC4-2272-1409-586DE1476CF9] The entity query filter requires the type property. in Wallee\Sdk\Service\AccountService->countWithHttpInfo() (Zeile 147 in /vendor/wallee/sdk/lib/Service/AccountService.php).

**Comment by thomashunziker** [comment]
@zehnplus-giannis We have fixed the example.

**Comment by ghost** [comment]
The example now gives me the following error

Wallee\Sdk\ApiException: [99280D14-A860-76C3-4BC5-AA548DCF371B] Error 401 connecting to the API (https://app-wallee.com:443/api/space/search) in Wallee\Sdk\ApiClient->callApi() (Zeile 466 in /vendor/wallee/sdk/lib/ApiClient.php).

**Comment by schurter-wallee** [comment]
This means, you application user in missing the permissions to read the space list.

**Comment by ghost** [comment]
I just assigned my application-user with all possible roles for Account, Subaccount and Space.
Error still appears.
Is there any documentation which guides through this whole process in detail?

**Comment by bummzack** [comment]
Having the same issue. @zehnplus-giannis were you able to solve this?

**Comment by vttn** [comment]
@bummzack 

Can you please open a new ticket and paste your error information in the new ticket.

Regards,

@vttn

**Comment by bummzack** [comment]
@vttn It's the same issue as this… trying to run the transaction example (second code example from here: https://github.com/wallee-payment/php-sdk/#configuring-a-service) and getting the following:

```
Uncaught Wallee\Sdk\ApiException: Error 401 connecting to the API (https://app-wallee.com:443/api/transaction/create?spaceId=XYZ) : Error // We need to force a reload when the back button is used in the browser. window.addEventListener( "popstate", function ( event ) { window.location.reload(true); }); Ooops! Sorry, something went wrong! Error code: 401 Please contact us and we will try to solve this issue. 
```

(I replaced the spaceID with `XYZ`)

**Comment by vttn** [comment]
Hello @bummzack 

It is most likely that your user credentials are not setup properly. You can also review our tests here https://github.com/wallee-payment/php-sdk/tree/master/test .

If this issue is still occurring for you, please reach out to our support https://wallee.com/support.html .

Regards,

@vttn

**Comment by bummzack** [comment]
Hi @vttn 
Thanks for your reply.
I'm trying to integrate Postfinance Checkout, maybe it's got something to do with that?
It's also not very helpful that the link that should point to "Learn how to authenticate and connect to our web service." is returning a 404:
https://checkout.postfinance.ch/doc/payment/doc/api/web-service#_authentication
https://app-wallee.com/doc/payment/doc/api/web-service#_authentication

**Comment by thomashunziker** [comment]
Dear Roman, 

Please get in contact with the guys from PostFinance checkout regarding this issue. They might be able to help you with this. The correct URL is: https://checkout.postfinance.ch/doc/api/web-service#_authentication

Regards,
Thomas

**Comment by bummzack** [comment]
For anybody having this issue with the Postfinance Checkout, just use https://github.com/pfpayments/php-sdk instead.
